apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: tomcat:9
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: war-volume
              mountPath: /usr/local/tomcat/webapps
      volumes:
        - name: war-volume
          emptyDir: {}  # This allows Spring Boot to copy WAR file
